[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "svetoch"
version = "0.1.0"
dependencies = ['numpy']

[project.optional-dependencies]
cuda = ['cupy']
